language: nodejs

before_script:
  - npm install -g @angular/cli
  - cd client/
  - npm i npm@latest -g
  - npm install
  - npm install codecov -g
  - npm install coveralls -g
  - npm install nyc -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
- npm run build
- ng test --watch=false --code-coverage

after_success:
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"