language: nodejs

before_scripts:
- cd client/
- npm install npm -g
- npm cache verify
- npm update
- npm install
- npm run build
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
 - npm install

scripts:
- npm run build