language: nodejs

addons:
  chrome: stable

before_script:
- cd client/
- npm install npm -g
- npm cache verify
- npm update
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- npm run build
