language: nodejs

cache:
  directories:
    - "node_modules"

install:
- npm install -g @angular/cli
- nvm install v8.9.1

before_script:
  - cd client/
  - npm install
  - npm install -g codecov
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
- npm run build
- ng test --watch=false --code-coverage
- codecov
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"