language: nodejs

before_script:
- cd client/
- npm i npm@latest -g
- npm install
- npm install codecov -g
- npm install coveralls -g
- npm install nyc -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run build
- nyc npm run test
- nyc report --reporter=text-lcov > coverage.lcov

after_success:
- codecov
- "cat ./coverage/lcov-report/lcov | ./node_modules/coveralls/bin/coveralls.js"