language: nodejs

before_script:
- cd client/
- npm install npm -g
- npm cache verify
- npm install

install:
- npm install

script:
- npm run build
- npm install codecov -g

after_scripts:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success:
- codecov