language: nodejs

before_script:
- cd client/
- npm install npm -g
- npm cache verify
- npm update
- npm install

install:
- npm install

script:
- npm run build
- npm install codecov -g

after_success:
- bash <(curl -s https://codecov.io/bash)